#!/usr/bin/ruby

require 'pathname'
APP_ROOT = File.join(File.dirname(Pathname.new(__FILE__).realpath))
require APP_ROOT + '/lib/vig.rb'

if !ARGV[0].nil? then
  gc = GoogleConnect.new

  File.open(ARGV[0]) do |f|
    @contents = f.read
  end

  gc.update_document(ARGV[0], @contents)

end
